apiVersion: v1
kind: Service
metadata:
  name: cloud-resource-optimizer-service
  labels:
    app: cloud-resource-optimizer
spec:
  selector:
    app: cloud-resource-optimizer
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: ClusterIP
